#!/bin/bash
set -uxo pipefail

usage() {
    echo 'USAGE: git-new <new-branch> [<copy-from-branch> [<repo>]]'
    echo
    exit -1
}

git diff-index --quiet HEAD --

if [ $? -ne 0 ]; then
    echo 'Changes in your workspace would be overwritten'
    exit -1
fi

if [[ -z $1 ]]; then
    usage
else
    new_branch=$1
fi

if [[ -z $2 ]]; then
    source_branch=jacktrip/dev
else
    source_branch=$2
fi

if [[ -z $3 ]]; then
    repo=origin
else
    repo=$3
fi

git fetch $source_branch
git checkout -b $new_branch $source_branch
git push $new_branch -u $repo
