#!/bin/bash

set -uxo pipefail

if [[ -z $1 ]]; then
    echo 'USAGE: git-new new_branch [source_branch [repo]]'
    exit -1
else
    new_branch=$1
fi

if [[ -z $2 ]]; then
    source_branch=jacktrip/dev
else
    source_branch=$2
fi

if [[ -z $3 ]]; then
    repo=origin
else
    repo=$3
fi

if git diff-index --quiet HEAD --; then
    git switch -c $new_branch
    git fetch $source_branch
    git reset --hard $source_branch
    git push $new_branch -u $repo
else
    echo 'Changes in your workspace would be overwritten'
    exit -1
fi
